server:
  port: 8081

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://120.79.162.32:3306/gulimall_pms
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 120.79.162.32:8848
  application:
      name: gulimall-product
mybatis-plus:
  mapper-locations: classpath:mapper/**/**Maper.xml